/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.tdas.pi3b.exaula02.principal;

import br.senac.tdas.pi3b.exaula02.alterar.CadastrarProduto;
import br.senac.tdas.pi3b.exaula02.alterar.ConsultarProduto;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author elvis
 */
public class Principal extends javax.swing.JFrame {
    
    private ConsultarProduto consultarProduto = null;
    private CadastrarProduto cadastrarProduto = null;
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    //metodos
    public ConsultarProduto getConsultarProduto() {
        return consultarProduto;
    }
    
    public void setConsultarProduto(ConsultarProduto consultarProduto) {
        this.consultarProduto = consultarProduto;
    }
    
    public CadastrarProduto getCadastrarProduto() {
        return cadastrarProduto;
    }
    
    public void setCadastrarProduto(CadastrarProduto cadastrarProduto) {
        this.cadastrarProduto = cadastrarProduto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPrincipal = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuAlterar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadastrarMouseClicked(evt);
            }
        });
        menu.add(menuCadastrar);

        menuAlterar.setText("Alterar/Excluir");
        menu.add(menuAlterar);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadastrarMouseClicked
        //Cadastrar Produto
        //verifica se a tela está vazia ou se ja não esta aberta
        if (cadastrarProduto == null || !cadastrarProduto.isDisplayable()) {
            cadastrarProduto = new CadastrarProduto();
            desktopPrincipal.add(cadastrarProduto);
            centralizarJanela(cadastrarProduto);
        }
        cadastrarProduto.toFront();
    }//GEN-LAST:event_menuCadastrarMouseClicked
    
    public void centralizarJanela(JInternalFrame jif) {
        Dimension desktopSize = desktopPrincipal.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPrincipal;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAlterar;
    private javax.swing.JMenu menuCadastrar;
    // End of variables declaration//GEN-END:variables
}
